modLoader = "javafml"
loaderVersion = "[1,)"

logoFile = "icon.png"
authors = "90"
license = "LGPLv3.0"

issueTrackerURL = "https://github.com/62832/AppliedE/issues"
displayURL = "https://github.com/62832/AppliedE"

[[mods]]
modId = "appliede"
version = "$version"
displayName = "AppliedE"
description = "Direct EMC integration with Applied Energistics 2."

[[dependencies]]
modId = "ae2"
type = "required"
versionRange = "[15.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies]]
modId = "projecte"
type = "required"
versionRange = "[1.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies]]
modId = "ae2wtlib"
type = "optional"
versionRange = "[15,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies]]
modId = "teamprojecte"
type = "optional"
versionRange = "[1.1.3,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies]]
modId = "aecapfix"
type = "optional"
versionRange = "[0.8,)"
ordering = "AFTER"
side = "SERVER"
